# デフォルト有効のルールのうち、無効にするもの
disabled_rules:
    #- block_based_kvo
    #- class_delegate_protocol
    #- closing_brace
    #- closure_parameter_position
    #- colon
    #- comma
    #- compiler_protocol_init
    #- control_statement
    #- custom_rules
    #- cyclomatic_complexity
    #- deployment_target
    #- discarded_notification_center_observer
    #- discouraged_direct_init
    #- duplicate_imports
    #- dynamic_inline
    #- empty_enum_arguments
    #- empty_parameters
    #- empty_parentheses_with_trailing_closure
    #- file_length
    #- for_where
    #- force_cast
    #- force_try
    #- function_body_length
    #- function_parameter_count
    #- generic_type_name
    #- identifier_name
    #- implicit_getter
    #- inert_defer
    #- is_disjoint
    #- large_tuple
    #- leading_whitespace
    #- legacy_cggeometry_functions
    #- legacy_constant
    #- legacy_constructor
    #- legacy_hashing
    #- legacy_nsgeometry_functions
    #- line_length
    #- mark
    #- multiple_closures_with_trailing_closure
    #- nesting
    #- no_fallthrough_only
    #- notification_center_detachment
    #- opening_brace
    #- operator_whitespace
    #- private_over_fileprivate
    #- private_unit_test
    #- protocol_property_accessors_order
    #- redundant_discardable_let
    #- redundant_objc_attribute
    #- redundant_optional_initialization
    #- redundant_set_access_control
    #- redundant_string_enum_value
    #- redundant_void_return
    #- return_arrow_whitespace
    #- shorthand_operator
    #- statement_position
    #- superfluous_disable_command
    #- switch_case_alignment
    #- syntactic_sugar
    #- todo
    #- trailing_comma
    #- trailing_newline
    #- trailing_semicolon
    #- trailing_whitespace
    #- type_body_length
    #- type_name
    #- unneeded_break_in_switch
    #- unused_closure_parameter
    #- unused_control_flow_label
    #- unused_enumerated
    #- unused_optional_binding
    #- unused_setter_value
    #- valid_ibinspectable
    #- vertical_parameter_alignment
    #- vertical_whitespace
    #- void_return
    #- weak_computed_property
    #- weak_delegate
    #- xctfail_message
# コードの記載のない改行を許可するため
- trailing_whitespace
# force_castは場合によっては使用するため
- force_cast
# closureが返す値を明示しておきたい場合があるため
- unused_closure_parameter

# デフォルト無効のルールのうち、有効にするもの
opt_in_rules:
- closure_end_indentation
- closure_spacing
- collection_alignment
- empty_count
- explicit_self
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- missing_docs
- nimble_operator
- number_separator
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports

# 追加したOSSライブラリは対象に含めない
excluded:
- Pods/
- Carthage/
- generated/R.generated.swift

# 1行あたりの文字数制限変更
line_length: 120

# 変数名に関する制約
identifier_name:
    allowed_symbols: "_"
    min_length: 2
    excluded:
    - i
    - j
    - n
    - x
    - y
